# Generated by Django 3.1.7 on 2021-03-30 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0005_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='administrator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
