# Generated by Django 3.1.7 on 2021-03-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_product'),
        ('designation', '0002_designation_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
