# Generated by Django 3.1.7 on 2021-04-04 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0003_designation_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='description',
            field=models.TextField(default='Designation Description', max_length=500),
        ),
    ]
