# Generated by Django 3.1.7 on 2021-03-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='Bug Title')),
                ('description', models.TextField(max_length=500, verbose_name='Bug Description')),
                ('ticket_status', models.CharField(choices=[('SUB', 'SUBMITTED'), ('REJ', 'REJECTED'), ('A&U', 'APPROVED AND UNASSIGNED'), ('A&A', 'APPROVED AND ASSIGNED'), ('POS', 'POSTPONED'), ('RES', 'RESOLVED'), ('CLO', 'CLOSED'), ('DUP', 'DUPLICATE')], default='SUB', max_length=3)),
                ('severity_level', models.CharField(choices=[('LOW', 'LOW'), ('MIN', 'MINOR'), ('MAJ', 'MAJOR'), ('CRI', 'CRITICAL')], max_length=3)),
                ('priority_level', models.CharField(choices=[('LOW', 'LOW'), ('MED', 'MEDIUM'), ('HIG', 'HIGH')], max_length=3)),
                ('public_view', models.BooleanField(default=False)),
            ],
        ),
    ]
