# Generated by Django 3.1.7 on 2021-03-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('SUB', 'SUBMITTED'), ('REJ', 'REJECTED'), ('A&U', 'APPROVED AND UNASSIGNED'), ('A&A', 'APPROVED AND ASSIGNED'), ('POS', 'POSTPONED'), ('RES', 'RESOLVED'), ('CLO', 'CLOSED'), ('DUP', 'DUPLICATE')], max_length=3),
        ),
    ]
