# Generated by Django 3.1.7 on 2021-03-31 10:26

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20210331_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.IntegerField(default=ticket.models.ticket_number_generator, unique=True),
        ),
    ]
