# Generated by Django 3.1.7 on 2021-03-31 10:38

from django.db import migrations, models
import ticket.ticket_number


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20210331_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.IntegerField(default=ticket.ticket_number.ticket_number_generator),
        ),
    ]
