# Generated by Django 3.1.7 on 2021-03-31 10:53

from django.db import migrations, models
import ticket.ticket_number


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20210331_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default=ticket.ticket_number.ticket_number_generator, editable=False, max_length=25),
        ),
    ]
