# Generated by Django 3.1.7 on 2021-03-31 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0008_ticket_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='submitted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MED', 'MEDIUM'), ('HIG', 'HIGH')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity_level',
            field=models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MIN', 'MINOR'), ('MAJ', 'MAJOR'), ('CRI', 'CRITICAL')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(blank=True, choices=[('SUB', 'SUBMITTED'), ('REJ', 'REJECTED'), ('A&U', 'APPROVED AND UNASSIGNED'), ('A&A', 'APPROVED AND ASSIGNED'), ('POS', 'POSTPONED'), ('RES', 'RESOLVED'), ('CLO', 'CLOSED'), ('DUP', 'DUPLICATE')], default='SUB', max_length=3, null=True),
        ),
    ]
