# Generated by Django 3.1.7 on 2021-04-04 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20210403_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='submitted_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
