# Generated by Django 3.1.7 on 2021-04-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_of_launch',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Product Description', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/product-logo/'),
        ),
    ]
