# Generated by Django 3.1.7 on 2021-03-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('designation', '0001_initial'),
        ('product', '0001_initial'),
        ('user', '0003_auto_20210304_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.ManyToManyField(blank=True, null=True, to='designation.Designation'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='product',
        ),
        migrations.AddField(
            model_name='user',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='product.Product'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, to='team.Team'),
        ),
    ]
