# Generated by Django 3.1.7 on 2021-03-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210304_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='company_associated',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='designation',
            new_name='designation_assigned',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='product',
            new_name='product_assigned',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='team',
            new_name='team_assigned',
        ),
    ]
