# Generated by Django 3.1.7 on 2021-04-04 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 19, 22, 3, 38752), editable=False),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default='Team Description', max_length=500),
        ),
    ]
