# Generated by Django 3.1.7 on 2021-04-04 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20210404_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 13, 56, 11, 560225, tzinfo=utc), editable=False),
        ),
    ]
